version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: Scripts/install_nginx.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/start_nginx.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: Scripts/validate_service.sh
      timeout: 300
      runas: root
