version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - mkdir -p build
  build:
    commands:
      - echo Build started on `date`
      - cp index.html build/
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - index.html
  base-directory: build
