version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - echo Installing nginx config...
  build:
    commands:
      - echo Build started on `date`
      - echo Copying web files...
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - index.html
  discard-paths: no