version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - mkdir -p build
  build:
    commands:
      - echo Build started on `date`
      - cp -r Scripts build/
      - cp index.html build/
      - cp appspec.yml build/
      - cp nginx.conf build/
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: build
