# .github/workflows/build.yml
name: Build and Deploy HTML with Nginx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    
    - name: Build and test nginx
      run: |
        docker build -t my-nginx-app .
        docker run -d -p 8080:80 --name test-container my-nginx-app
        sleep 5
        curl http://localhost:8080 || exit 1
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: website
        path: index.html

    - name: Cleanup
      run: docker rm -f test-container